### ISSUE TITLE
chromium not installing

### ISSUE THREAD

**Issue by v-tan** [dtolstyi/node-chromium#14]
Hi, 
I was trying to download on my mac but couldn't because of an error restricting me. Please have a look at it. Thanks.

**System** : mac Mojave
**the command used** : `npm install --save chromium` / `npm install chromium`
**results/bug shown** : 

node install.js

async function downloadChromiumRevision(revision) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)

**Comment by dtolstyi** [comment]
Hi @v-tan. Are you sure that you are using node version that supports `async` functions?

> node-chromium 2.x.x is tested against and supports Node.js 7+
> If you need to use older versions of Node.js try node-chromium 1.x.x releases.

**Comment by v-tan** [comment]
I updated the node.js version and install worked. Thanks.

**Comment by dtolstyi** [comment]
> I updated the node.js version and install worked. Thanks.

You are very welcome Varun! Good luck!

Kind regards,
Dmytro
